# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monday Game Group
email: daniel.dennerkrans@hyperisland.se
description: > # An attempt to create and maintain a wiki about the adventures we, a solid group of friends around a kitchen table, embark on every Monday.
baseurl: "http://dennerkrans.github.io/monday-game-group" # the subpath of your site, e.g. /blog
url: "http://dennerkrans.github.io/monday-game-group" # the base hostname & protocol for your site
twitter_username: dennerkrans
github_username:  dennerkrans

# Build settings
markdown: kramdown
